### ISSUE TITLE
Cannot Catch SocketException

### ISSUE THREAD

**Issue by wolframm** [isoos/postgresql-dart#279] opened 2024-01-14 06:24 UTC
When attempting connection to a Postgres instance running in local Docker that is not yet fully initialized (container is running, but Postgres server is not quite ready yet), the following error is thrown:

`SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = localhost, port = 6...`

Normally I run `await Connection.open(...)` in a `for`-loop with `Future.delayed(...)` a few times and return when connection is successful (no more exceptions). However, in this case, `SocketException` is simply never caught, no matter what I try. Therefore, I can't retry `Connection.open(...)`.

How can I catch `SocketException`?

```
import 'dart:async';
import 'dart:io';

import 'package:pb_server/pb_server.dart';

Connection? _connection;

Future<void> openConnection(ServerArgs serverArgs) async {
  if (_connection != null) return;
  for (int i = 0; i < 9; i++) {
    await Future.delayed(Duration(milliseconds: 200));
    _connection = await getConnection(serverArgs);
    if (_connection != null) {
      final serverTime = (await _connection!.execute('select now()'))[0][0];
      return;
    }
   print('Connection attempt ${i + 1} unsuccessful. Trying again.');
  }
 print('Could not connect');
}

Future<Connection?> getConnection(ServerArgs serverArgs) async {
  try {
    return await Connection.open(serverArgs.endpoint,
        settings: ConnectionSettings(sslMode: SslMode.disable));
  } on SocketException {
    print('db service unavailable');
    return null;
  } catch (e) {
    print(e);
    return null;
  }
}
```

**Comment by wolframm** [comment] 2024-01-14 06:44
I used the following hack to fix it:

```
Future<Connection?> getConnection(ServerArgs serverArgs) async {
  Connection? connection;
  bool? okay;
  runZonedGuarded(() async {
    connection = await Connection.open(serverArgs.endpoint, settings: ConnectionSettings(sslMode: SslMode.disable));
    okay = true;
  }, (e, s) {
    print(e);
    okay = false;
  });
  while (true) {
    await Future.delayed(Duration(milliseconds: 100));
    if (okay == null) {
      continue;
    } else {
      return connection;
    }
  }
}
```
Perhaps something similar should be included in the `Connection.open()` function, but instead of returning `null` the function could throw some exception that could more easily be caught by `postgres` library users.

**Comment by isoos** [comment] 2024-01-14 09:35
Not sure what is the difference between your use case and these tests:
https://github.com/isoos/postgresql-dart/blob/master/test/connection_test.dart#L341-L379

`Connection.open` should fail hard after timeout or if it is unable to connect, and should not generate uncaught exception outside of that call. It would be nice if we could have a reproducible use case to debug it.

**Comment by wolframm** [comment] 2024-01-15 12:48
I have a dev tool CLI written in Dart that starts a Postgres docker container and then immediately tries to connect to apply some SQL files. The uncaught `SocketException` emerges during the first couple of connection attempts when the db server is probably still initializing. 

I'll let you know when I publish my tool on `pub.dev` then perhaps debugging is possible.

**Comment by wolframm** [comment] 2024-01-15 12:51
That sounds like the cleanest solution.

**Comment by simolus3** [comment] 2024-01-29 20:49
We still shouldn't have unhandled exceptions anywhere in the library, especially since the open process is asynchronous and can report these problems. This will be fixed by https://github.com/isoos/postgresql-dart/pull/285, but I'm not sure how to test it reliably.

**Closed** 2024-01-29 23:04 UTC
