### ISSUE TITLE
SocketException: Broken Pipe

### ISSUE THREAD

**Issue by busslina** [isoos/postgresql-dart#295] opened 2024-02-15 13:26 UTC
I wake up today and saw that my server was reinitiated at 7AM. Checking the Systemd log file I got:
`Unhandled exception:
Feb 15 06:17:46 server1.busslina.com dart[87776]: SocketException: Broken pipe (OS Error: Broken pipe, errno = 32), ...`

I suppose it is the connection to the database. Can anyone suggest me how to deal with it and try to reconnect?

Also, would be great you  to include this info (along side to catch connecting exception) on the README.md, because for me it's one of the main worries about dealing with a database, and maybe for more people too.

Congrats about this great lib that works great.

Thanks.

**Comment by busslina** [comment] 2024-02-15 13:30
Must I try/catch every `execute` in order to prevent my app crashes when this exception occurs?

Must I try/catch on `Connection.open` too when establishing the connection?

**Comment by isoos** [comment] 2024-02-15 22:37
I think this is  duplicate of #290, closing to keep only one issue open.

Note: I think a single `Connection` object is just that: it works as long as the underlying socket connection is open. If there is a problem, all bets are off. However, `Pool.run()` and `Pool.runTx()` would be ideal for retrying the connection failures (see other issue).

**Closed by isoos** 2024-02-15 22:37 UTC
